title: "Vernon R. King, III"
description: "A collection of writings and updates from Vernon R. King, III: Follower of Jesus. Husband to Katie. Father to many. Student at SEBTS."
keywords: ["Vernon R. King III", "PJ King", "PJ", "Vernon", "Christian", "Christ", "God", "Lord", "church", "ecclesiology", "baptist", "SBC", "gospel"] 
url: http://www.vernonking.org
files: http://www.vernonking.org/files

# Owner/author information
owner:
  name:           Vernon King
  email:          mail@vernonking.org
  twitter:        vrking3
  facebook:       pjking07
  broadcast:      "http://broadcast.app.net/44043/vernonkingorg/"
  amazon:         "vernonking-20"
  goodreads:      pjking07
  github:         
    user:         pjking07
    repo:         vernonking.org

analytics:
    google:
        code:     UA-47683767-1
        name:     vernonking.org
    #gosquared:  GSN-467829-L

# Links to include in top navigation
# For external links add external: true
links:
  - title: CV
    url: /cv/
  - title: Sermons
    url: /sermons/
  - title: Papers
    url: /papers/
  - title: Reviews
    url: /reviews/
  - title: Archives
    url: /archives/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
redcarpet:
  extensions: ['smart', 'tables', 'no_intra_emphasis', 'autolink', 'footnotes', 'superscript']
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/
relative_permalinks: false

sass:
    style: :compressed
    sass_dir: assets/sass

archive:
    month_format: "%Y-%b"

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "LICENSE", "Gemfile", "CNAME", "*.sh", "*.pxm"]

color:
  darkblue:  24536b
  lightblue: 8AB9D1